### PR TITLE
Fix documentation for #8

### PR DESCRIPTION
**Pull request by SimchaShats**
Fix documentation for pie diagram

### CODE REVIEW

**Comment by marzolfb** [comment]
Thank for updating the readme - this is helpful. 

Before I can accept this and merge it in, I need you to sign [our Contributor License Agreement (CLA)](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform). This will take care of us for this PR and any future ones you may want to submit.

**Comment by SimchaShats** [comment]
Done

**Comment by marzolfb** [comment]
Wonderful. Thank you. One more thing. Since the Example Data section of the readme is basically a straight copy/paste from the example/data.js file - could you update that file as well for consistency? At some point, that section in the readme should maybe just be a link to the example data directly rather than embedded as it is now.

**Comment by SimchaShats** [comment]
Done

**Pull request merged**
