### PR TITLE
make some performance-improving changes and add the new candlestick chart type

### PR DESCRIPTION
**Pull request by liuliangsir**
Thank you for contributing a pull request. 

Please ensure that you have signed the [CLA](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform).

- [x] I have signed the CLA

### CODE REVIEW

**Comment by marzolfb** [comment]
I also just got started reviewing and there are a couple of things that should be addressed right from the start.

First, the whitespace/semicolon changes you made make it difficult to see where actual changes occurred - even after using Github's "?w=1" trick to ignore whitespace. Would it be possible to clean that up and try to retain the formatting of the original source where possible?

Second, there are several conflicting files and I just pushed some other PRs to master. Could you work on getting all these conflicts resolved?

Still need to dive further into these changes, but it looks like in some areas, you decided to go with basically a complete rewrite of some chart types. Could you provide more detail on what your motivations were to make these changes and how you evaluated performance problems and potential areas for optimization?

**Comment by marzolfb** [comment]
@liuliangsir2016 Any update on this? Do you have any answers to the review questions above?

**Comment by liuliangsir** [comment]
@marzolfb sorry
Recently, i am so busy in resolving bugs as releasing new app version
That is to say, i forget to fix these conficts
So, i am going to make a new pull request
I am so glad to  your reply

**Comment by marzolfb** [comment]
Closing based on age of pull request and lack of response.

**Pull request closed without merging**
