### PR TITLE
Added new demo image to README

### PR DESCRIPTION
**Pull request by marzolfb**

### CODE REVIEW

**Comment by katscott** [comment]
I think these should be in the wiki...
And probably best as a static image for each type on the types page

**Comment by marzolfb** [comment]
I like the idea of static images for each chart type on each of the wiki pages but why not additionally have some demo image on the front page. I think having a demo visual of some kind is a fairly common practice on readmes. It's also natural for first time visitors to wonder what these charts look like and it seems fitting to provide this on the readme.

**Comment by marzolfb** [comment]
Is the animated gif objectionable? Would it be best to just pick a couple of chart types and show a couple static images instead? Or is the objection to any kind of demo visual on the readme?

**Comment by marzolfb** [comment]
Ok, I replaced the animated gif with a series of 5 chart images. Perhaps this is a decent alternative.

**Pull request merged**
