### PR TITLE
Upgrade to RN 0.47.2

### PR DESCRIPTION
**Pull request by Minishlink**
Thank you for contributing a pull request. 

Please ensure that you have signed the [CLA](https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform).

- [x] I have signed the CLA

This is backwards compatible.

### CODE REVIEW

**Comment by Emilios1995** [comment]
the upgrade of react-native-svg is important in order for this to run on android. 
Please merge .

**Comment by marzolfb** [comment]
@Minishlink Any chance you can test the change for ios? I ran into this problem: https://github.com/facebook/react-native/issues/14935.

This will need to be fixed before merging.

**Comment by Minishlink** [comment]
@marzolfb Are you talking about the Example app? It seems like the upgrade to 0.46 wasn't done with `react-native-git-upgrade`, I'll commit a fix.

**Comment by marzolfb** [comment]
Yes. Sorry for not being clear. Thanks for the additional commit.

**Comment by Minishlink** [comment]
Thanks!

**Pull request merged**
